-- =====================================================================
-- SecureChat — COMPLETE SUPABASE SQL SETUP (FINAL)
-- auth.users.id is UUID — all user ID columns are UUID.
-- Run this entire script in your Supabase SQL Editor.
-- =====================================================================


-- =====================================================================
-- STEP 0: CLEAN SLATE
-- =====================================================================

DROP TRIGGER  IF EXISTS on_auth_user_created     ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

DROP TABLE IF EXISTS public.messages             CASCADE;
DROP TABLE IF EXISTS public.room_participants    CASCADE;
DROP TABLE IF EXISTS public.rooms               CASCADE;
DROP TABLE IF EXISTS public.profiles            CASCADE;


-- =====================================================================
-- STEP 1: EXTENSIONS
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- =====================================================================
-- STEP 2: TABLES
-- =====================================================================

-- 2a. Profiles
CREATE TABLE public.profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username    VARCHAR(255) UNIQUE,
    public_key  TEXT,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2b. Chat Rooms
CREATE TABLE public.rooms (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255),
    type        VARCHAR(50) NOT NULL CHECK (type IN ('room', 'direct')),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2c. Room Participants
CREATE TABLE public.room_participants (
    room_id     UUID NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    joined_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (room_id, user_id)
);

-- 2d. Encrypted Messages
CREATE TABLE public.messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id           UUID NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
    sender_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
    encrypted_content TEXT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);


-- =====================================================================
-- STEP 3: INDEXES
-- =====================================================================

CREATE INDEX idx_room_participants_user_id
    ON public.room_participants(user_id);

CREATE INDEX idx_messages_room_id_created_at
    ON public.messages(room_id, created_at DESC);

CREATE INDEX idx_profiles_username
    ON public.profiles(username);


-- =====================================================================
-- STEP 4: TRIGGER — Auto-create profile on signup
-- =====================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  default_username TEXT;
BEGIN
  SELECT COALESCE(
    NULLIF(SPLIT_PART(NEW.email, '@', 1), ''),
    'user_' || SUBSTRING(NEW.id::TEXT FROM 1 FOR 8)
  ) INTO default_username;

  INSERT INTO public.profiles (id, username, public_key)
  VALUES (NEW.id, default_username, NULL)
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- =====================================================================
-- STEP 5: ENABLE ROW LEVEL SECURITY
-- =====================================================================

ALTER TABLE public.profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages          ENABLE ROW LEVEL SECURITY;


-- =====================================================================
-- STEP 6: RLS POLICIES
-- =====================================================================

-- PROFILES --
CREATE POLICY "profiles_select"
ON public.profiles FOR SELECT TO authenticated
USING (true);

CREATE POLICY "profiles_insert"
ON public.profiles FOR INSERT TO authenticated
WITH CHECK (auth.uid() = id);

CREATE POLICY "profiles_update"
ON public.profiles FOR UPDATE TO authenticated
USING  (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- ROOMS --
CREATE POLICY "rooms_select"
ON public.rooms FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = rooms.id
          AND room_participants.user_id = auth.uid()
    )
);

CREATE POLICY "rooms_insert"
ON public.rooms FOR INSERT TO authenticated
WITH CHECK (true);

-- ROOM PARTICIPANTS --
CREATE POLICY "room_participants_select"
ON public.room_participants FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.room_participants AS rp
        WHERE rp.room_id = room_participants.room_id
          AND rp.user_id = auth.uid()
    )
);

CREATE POLICY "room_participants_insert"
ON public.room_participants FOR INSERT TO authenticated
WITH CHECK (true);

CREATE POLICY "room_participants_delete"
ON public.room_participants FOR DELETE TO authenticated
USING (user_id = auth.uid());

-- MESSAGES --
CREATE POLICY "messages_select"
ON public.messages FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = messages.room_id
          AND room_participants.user_id = auth.uid()
    )
);

CREATE POLICY "messages_insert"
ON public.messages FOR INSERT TO authenticated
WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = messages.room_id
          AND room_participants.user_id = auth.uid()
    )
);


-- =====================================================================
-- STEP 7: REALTIME
-- =====================================================================

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END;
$$;


-- =====================================================================
-- DONE!
-- =====================================================================
