-- =====================================================================
-- COMPLETE SUPABASE / POSTGRESQL DATABASE SETUP FOR SECURECHAT (REACT)
-- =====================================================================
-- Run this script in your Supabase SQL Editor (or PostgreSQL database)
-- to create all required tables, triggers, indexes, and RLS policies.
-- =====================================================================

-- Enable pgcrypto extension for UUID generation if needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================================
-- 1. TABLE DEFINITIONS
-- =====================================================================

-- Profiles Table (linked to Supabase Auth auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    public_key TEXT, -- Base64 RSA public key for end-to-end client-side encryption
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Chat Rooms / Channels Table
CREATE TABLE IF NOT EXISTS public.rooms (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(255), -- NULL for Direct Messages (DMs)
    type VARCHAR(50) NOT NULL CHECK (type IN ('room', 'direct')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Room Participants Join Table
CREATE TABLE IF NOT EXISTS public.room_participants (
    room_id UUID REFERENCES public.rooms(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (room_id, user_id)
);

-- Encrypted Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID REFERENCES public.rooms(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL NOT NULL,
    encrypted_content TEXT NOT NULL, -- Encrypted message payload
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- =====================================================================
-- 2. INDEXES FOR HIGH PERFORMANCE
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_room_participants_user_id ON public.room_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_room_id_created_at ON public.messages(room_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);

-- =====================================================================
-- 3. AUTOMATIC PROFILE CREATION TRIGGER ON AUTH SIGNUP
-- =====================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, public_key)
  VALUES (
    NEW.id,
    COALESCE(
      SPLIT_PART(NEW.email, '@', 1), 
      'user_' || SUBSTRING(NEW.id::TEXT FROM 1 FOR 8)
    ),
    NULL
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists to allow idempotent re-running
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW 
  EXECUTE FUNCTION public.handle_new_user();

-- =====================================================================
-- 4. ROW-LEVEL SECURITY (RLS) POLICIES
-- =====================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- PROFILES POLICIES
-- ---------------------------------------------------------------------

DROP POLICY IF EXISTS "Allow public select for authenticated users" ON public.profiles;
CREATE POLICY "Allow public select for authenticated users" 
ON public.profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow owners to insert profile" ON public.profiles;
CREATE POLICY "Allow owners to insert profile" 
ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Allow owners to update profile" ON public.profiles;
CREATE POLICY "Allow owners to update profile" 
ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- ---------------------------------------------------------------------
-- ROOMS POLICIES
-- ---------------------------------------------------------------------

DROP POLICY IF EXISTS "Allow select for room participants" ON public.rooms;
CREATE POLICY "Allow select for room participants" 
ON public.rooms FOR SELECT TO authenticated USING (
    EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = id AND room_participants.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow room insertion for authenticated users" ON public.rooms;
CREATE POLICY "Allow room insertion for authenticated users" 
ON public.rooms FOR INSERT TO authenticated WITH CHECK (true);

-- ---------------------------------------------------------------------
-- ROOM PARTICIPANTS POLICIES
-- ---------------------------------------------------------------------

DROP POLICY IF EXISTS "Allow select for room members" ON public.room_participants;
CREATE POLICY "Allow select for room members" 
ON public.room_participants FOR SELECT TO authenticated USING (
    EXISTS (
        SELECT 1 FROM public.room_participants AS rp
        WHERE rp.room_id = room_id AND rp.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow members creation" ON public.room_participants;
CREATE POLICY "Allow members creation" 
ON public.room_participants FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow users to delete their own participation" ON public.room_participants;
CREATE POLICY "Allow users to delete their own participation" 
ON public.room_participants FOR DELETE TO authenticated USING (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- MESSAGES POLICIES
-- ---------------------------------------------------------------------

DROP POLICY IF EXISTS "Allow select messages for room participants" ON public.messages;
CREATE POLICY "Allow select messages for room participants" 
ON public.messages FOR SELECT TO authenticated USING (
    EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = room_id AND room_participants.user_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Allow insert messages for room participants" ON public.messages;
CREATE POLICY "Allow insert messages for room participants" 
ON public.messages FOR INSERT TO authenticated WITH CHECK (
    sender_id = auth.uid() AND
    EXISTS (
        SELECT 1 FROM public.room_participants
        WHERE room_participants.room_id = room_id AND room_participants.user_id = auth.uid()
    )
);

-- =====================================================================
-- 5. REALTIME PUBLICATION FOR MESSAGES
-- =====================================================================
-- Enables Supabase Realtime subscriptions on messages table
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
